<a href="https://colab.research.google.com/github/XiaoLiang28/Datamanagement/blob/main/class2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
x = np.zeros([3,3])
print(x,type(x))
y=[1,2,3,4,5]
np.mean(y)
print(np.mean(y))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>


np.float64(3.0)

In [7]:
a=np.random.randint(1,9,10)
b=list(a)
print(a)
print(b)
z=np.random.binomial(1,0.8,20) #one code flip, 0.8 prob of 1(0.2 prob of 0), 20 draws
print(x)
zx=np.random.uniform(0,1,20) #20 draws between 0 and 1
print(zx)
print(np.sum(zx))


[7 8 1 7 3 3 3 4 8 2]
[np.int64(7), np.int64(8), np.int64(1), np.int64(7), np.int64(3), np.int64(3), np.int64(3), np.int64(4), np.int64(8), np.int64(2)]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0.06170461 0.42350022 0.31712009 0.80135278 0.18751256 0.88895987
 0.20685676 0.45144418 0.32249755 0.04087897 0.11107072 0.79593973
 0.5890693  0.05454873 0.65578958 0.20006612 0.72326051 0.57931812
 0.12688818 0.63003163]
8.167810188834151


In [11]:
# dictionary
D={}
print(D,type(D))
D={0:"C",1:"D"}
print(D)
# print(len(0)) # Removed incorrect len() call
print(D[0]) # Changed to access dictionary value by key
Dz={"France": "Paris","Italy":"Rome"} # Corrected dictionary syntax
print(Dz["Italy"])
Dz["Spain"]="M" # Changed to access dictionary value by key
for i in Dz:
  print(f"thecapital of {i} is {Dz[i]}")

{} <class 'dict'>
{0: 'C', 1: 'D'}
C
Rome
thecapital of France is Paris
thecapital of Italy is Rome
thecapital of Spain is M


In [15]:
import copy
x=[1,2,3,4,5]
x2=copy.copy(x)
x[0]=9
print(x,x2)
x3=copy.deepcopy(x) # deep copy, always works (included nested objects)

[9, 2, 3, 4, 5] [1, 2, 3, 4, 5]


In [21]:
#creating user defined functions
# this funtion prints a result; does not return a value
def print_capital(dictionary,country):
  print(f"The capital of {country} is {dictionary[country]}")

print_capital(Dz, "France")

for i in Dz:
  print_capital(Dz,i)

The capital of France is Paris
The capital of France is Paris
The capital of Italy is Rome
The capital of Spain is M


In [23]:
def return_capital(dictionary2,country2):
  print(f"the capital of {country2} is {dictionary2[country2]}")
  return dictionary2[country2]

mycapital = return_capital(Dz,"Italy")
print(mycapital)

the capital of Italy is Rome
Rome
